env: ruby
ruby:
  log_level: info
  amqp:
    host: localhost
    port: 5672
    username: travis_worker
    password: travis_worker_password
    virtual_host: travis.development
  vms:
    count: 1
    vbox_home: '/usr/lib/virtualbox'
timeouts:
  install: 600
  before_script: 480
  script: 1500
