env: staging
production:
  shell:
    buffer: 0.75
staging:
  shell:
    buffer: 1
  amqp:
    host: [host]
    port: [port]
    username: [username]
    password: [password]
    virtual_host: [virtual_host]


